---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base:10.0.10
  amd64: ghcr.io/hassio-addons/ubuntu-base:10.0.10
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
